name: Tests and deploiement of ceri-m2-ecommerce-2022
on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]

jobs:

  unit_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Tests with unittest
        run: |
          pip install --no-cache-dir --upgrade -r backend/requirements.txt
          pip install -e backend/.
          python backend/tests/unit_tests.py
     
      - name: Pylint
        run: |
          pylint --fail-under=9 backend/.

  build:
    needs: unit_test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Building docker images and push to the registry
        run: |
          docker login -u _json_key_base64 -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/purplepig
          docker build -t backend -f backend.Dockerfile .
          docker build -t frontend -f frontend.Dockerfile .
          docker tag backend europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/purplepig/backend:0.0.1
          docker tag frontend europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/purplepig/frontend:0.0.1
          docker push europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/purplepig/backend:0.0.1
          docker push europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/purplepig/frontend:0.0.1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: terraform
    
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} 
      - run: terraform init
      - run: terraform apply -auto-approve -input=False